# Numpy basic commands - A quick look

## This notebook is created for a quick peek at some commonly used numpy commands while practicing Data Science. However, this notebook covers some basics commands only.

#### Importing the numpy library

In [1]:
import numpy as np

#### Creating a numpy array

In [3]:
array_name = np.array([1,2,3,4,5])
array_name

array([1, 2, 3, 4, 5])

#### Converting a list to an array

In [4]:
list_name = [1,2,3,4,5]
type(list_name)

list

In [5]:
list_name = np.array(list_name)
list_name

array([1, 2, 3, 4, 5])

#### Getting the shape of the numpy array

In [7]:
np.shape(array_name)

(5,)

#### Reshaping a 1-D array to 2-D matrix

In [10]:
sample = np.array([1,2,3,4,5,6,7,8,9])
np.shape(sample)

(9,)

In [11]:
sample = sample.reshape(3,3) # the parameters are the dimensions of the resultant array to which you are reshaping.
np.shape(sample)

(3, 3)

#### Reshaping the array to multidimensional matrix

In [12]:
sample = np.array([1,2,3,4,5,6,7,8])
sample = sample.reshape(2,2,2)
sample

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
np.shape(sample)

(2, 2, 2)

#### Creating an array of equally spaced values within a range

In [15]:
sample = np.arange(-5,5,1) #First parameter - starting value.  Second parameter - Ending value (exclusive). Third Parameter - Interval size
sample

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [18]:
sample = np.arange(-1,1,0.1)
sample

array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
        -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
        -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
         2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
         5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
         8.00000000e-01,   9.00000000e-01])

#### Random array from a normalized distribution

In [21]:
from numpy import random as ra

In [24]:
sample = ra.randn(5,5)
sample

array([[-0.60149785, -1.1389865 ,  0.70006724, -0.16102534, -2.39460018],
       [ 1.28966206,  2.55613258, -0.79330974, -0.40622818,  0.0469819 ],
       [-0.37990423, -0.22033084,  1.27894072,  0.96201861,  1.40411351],
       [-0.22222286, -0.25130264,  0.23838382, -1.41396066,  0.4493223 ],
       [ 1.02440002,  1.42409796,  0.95664102,  0.35019677, -3.33657333]])

#### Creating a meshgrid of array values using numpy

In [29]:
values = [1,2,3,4,5,6,7,8,9,10]
x,y = np.meshgrid(values,values)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [27]:
y

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

### List Comprehension with / without numpy

#### Without numpy

In [36]:
# List comprehension is used to fill values in an array based on some boolean logic between some values.

A = [1,2,3,4,5]
B = [100,200,300,400,500]
condition = [True,True,False,False,True]
comprehend = [(A_val if(cond) else B_val) for A_val,B_val,cond in zip(A,B,condition)]
comprehend

[1, 2, 300, 400, 5]

#### With numpy

In [37]:
#List comprehension using numpy "where" function.
#Syntax:
#      First parameter - condition to evaluate
#      Second parameter - Value to return if condition is true
#      Third parameter - Value to return if condition is false


A = [1,2,3,4,5]
B = [100,200,300,400,500]
condition = [True,True,False,False,True]
comprehend = np.where(condition,A,B)
comprehend

array([  1,   2, 300, 400,   5])

#### Printing the unique values in a numpy array

In [38]:
fruits = np.array(['Apple','Mango','Orange','Mango','Apple','Apple','Bananas','Orange','Bananas','Orange','Mango','Grapes','Apple','Watermelon','Grapes','Bananas'])
np.unique(fruits)

array(['Apple', 'Bananas', 'Grapes', 'Mango', 'Orange', 'Watermelon'],
      dtype='<U10')

### Basic measures

#### Mean of values in array

In [48]:
sample = np.array([1,2,3,4,54,56,78,6,42,45,78,98,332])
np.mean(sample)

61.46153846153846

#### Standard Deviation of values in array

In [49]:
np.std(sample)

84.48724563243978

#### Sum of values in array

In [50]:
np.sum(sample)

799

#### Minimum Maximum values in array

In [53]:
min = np.min(sample)
max = np.max(sample)
min

1

In [54]:
max

332

#### Indices of minimum and maximum values in array

In [55]:
min = np.argmin(sample)
max = np.argmax(sample)
min

0

In [57]:
max

12

## Thanks for reading.